variable env {}
variable zone {}
variable image {}
variable disk_size {}
variable regionshort {}
variable machine_type {}
variable interface  {}
variable policy_name {}
variable kube_subnetwork {}
variable external_ip {}
